import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alec.Tunbridge' at '31/03/16 16:08' with Gradle 1.10
 *
 * @author Alec.Tunbridge, @date 31/03/16 16:08
 */
public class WordChains {
    public boolean readFile() throws URISyntaxException, IOException {
        Path path = Paths.get(ClassLoader.getSystemResource("words.txt").toURI());
        try(Stream<String> lines = Files.lines(path, Charset.forName("ISO-8859-1"))){
            lines.forEach(System.out::println);
        }
        return true;
    }

    public List<String> getWordChain(List<String> dictionary, String start, String end) {
        List<String> wordChain = new ArrayList<>();


        return wordChain;
    }

    public List<String> getSingleDifferenceWords(String word, List<String> dictionary) {
        List<String> singleDifferenceWords = new ArrayList<>();

        return singleDifferenceWords;

    }

    public boolean isWordSingleDifference(String givenWord, String compareWord){
        boolean isSingleDifference = false;

        return false;
    }





}
