import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Alec.Tunbridge' at '31/03/16 16:08' with Gradle 1.10
 *
 * @author Alec.Tunbridge, @date 31/03/16 16:08
 */
public class WordChainsTest {
    private WordChains wordChains;
    @Ignore
    @Test public void readFile() throws IOException, URISyntaxException {
        WordChains classUnderTest = new WordChains();
        assertThat(classUnderTest.readFile()).isTrue();
    }

    @Before
    public void setup() {
        wordChains = new WordChains();
    }

    @Test
    public void findWordsOfSameLength() {
        List<String> words = new ArrayList<>(Arrays.asList(new String[]{"bob", "bib", "bap", "to", "boat"}));
        List<String> result = wordChains.findWordsOfGivenLength(words, 3);
        assertThat(result).hasSize(3).contains("bob", "bib", "bap");
    }

    @Test
    public void distanceOfOne() {
        assertThat(wordChains.areOneApart("cat", "cot")).isTrue();
        assertThat(wordChains.areOneApart("cat", "dot")).isFalse();
    }

    @Test
    public void answerWithDistanceOfOne(){
        assertThat(wordChains.wordChain("cat","cot")).hasSize(2).containsExactly("cat","cot");
    }
}
