import org.junit.Test;

import java.io.IOException;
import java.net.URISyntaxException;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Alec.Tunbridge' at '31/03/16 16:08' with Gradle 1.10
 *
 * @author Alec.Tunbridge, @date 31/03/16 16:08
 */
public class WordChainsTest {
    @Test public void readFile() throws IOException, URISyntaxException {
        WordChains classUnderTest = new WordChains();
        assertTrue("readFile should return 'true'", classUnderTest.readFile());
    }
}
